# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'end.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import json


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnswerWindow(object):
    def setupUi(self, AnswerWindow):
        AnswerWindow.setObjectName("AnswerWindow")
        AnswerWindow.resize(1280, 720)

        self.center(AnswerWindow)
        
        self.background = QtWidgets.QLabel(AnswerWindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "whole_background.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.background.setPixmap(pixmap)
                self.background.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(AnswerWindow)
        self.frame.setGeometry(QtCore.QRect(160, 64, 960, 572))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 80px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(560, 120, 296, 296))
        self.label.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "med_cross_bright.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.label.setPixmap(pixmap)
                self.label.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")
        self.label.setObjectName("label")
        self.place_for_answer = QtWidgets.QTextEdit(self.frame)
        self.place_for_answer.setGeometry(QtCore.QRect(96, 112, 408, 408))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.place_for_answer.setFont(font)
        self.place_for_answer.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 5px solid rgb(0,39,3);\n"
"border-radius: 19px;\n"
"color: rgb(0, 42, 5);")
        self.place_for_answer.setObjectName("place_for_answer")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(136, 48, 322, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman [Mono]")
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 42, 5);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(AnswerWindow)
        self.label_2.setGeometry(QtCore.QRect(280, 640, 728, 59))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(102, 102, 102);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.mishka = QtWidgets.QPushButton(self.frame)
        self.mishka.setGeometry(QtCore.QRect(675, 230, 74, 74))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mishka.setFont(font)
        self.mishka.setStyleSheet("background-color: rgba(42, 42, 42, 0);")
        self.mishka.setObjectName("mishka")

        self.load_answer_text()

        self.retranslateUi(AnswerWindow)
        QtCore.QMetaObject.connectSlotsByName(AnswerWindow)

    
    def load_answer_text():
        try:
            # Получаем абсолютный путь к директории текущего скрипта
            script_dir = os.path.dirname(os.path.abspath(__file__))
            # Формируем абсолютный путь к файлу answer.txt
            answer_path = os.path.join(script_dir, "answer.txt")
            
            if not os.path.exists(answer_path):
                raise FileNotFoundError(f"Файл answer.txt не найден по пути: {answer_path}")
            
            with open(answer_path, 'r', encoding='utf-8') as file:
                return file.read()
                
        except Exception as e:
            error_msg = f"Ошибка при загрузке файла ответа: {str(e)}"
            print(error_msg)  # Для отладки
            return error_msg


    def retranslateUi(self, AnswerWindow):
        _translate = QtCore.QCoreApplication.translate
        AnswerWindow.setWindowTitle(_translate("AnswerWindow", "HealthTrack"))
        self.label_3.setText(_translate("AnswerWindow", "Ответ нейросети:"))
        self.mishka.setText(_translate("AnswerWindow", ""))
        self.label_2.setText(_translate("AnswerWindow", "Авторы приложения не несут ответсвенности за Ваше здоровье. \n"
"Обязательно проконсультируйтесь с врачом."))

    def center(self, window):
        # Получаем геометрию основного экрана
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        # Получаем геометрию окна
        window_geometry = window.frameGeometry()
        # Центрируем окно
        window_geometry.moveCenter(screen.center())
        # Перемещаем окно в центр экрана
        window.move(window_geometry.topLeft())
