# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cat_wind(object):
    def setupUi(self, Cat_wind):
        Cat_wind.setObjectName("Cat_wind")
        Cat_wind.resize(1280, 960)

        self.center(Cat_wind)

        Cat_wind.setMinimumSize(QtCore.QSize(1280, 960))
        Cat_wind.setMaximumSize(QtCore.QSize(1280, 960))
        self.label = QtWidgets.QLabel(Cat_wind)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 960))
        self.label.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "king.jpg")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.label.setPixmap(pixmap)
                self.label.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")
        self.label.setObjectName("label")

        self.retranslateUi(Cat_wind)
        QtCore.QMetaObject.connectSlotsByName(Cat_wind)

    def retranslateUi(self, Cat_wind):
        _translate = QtCore.QCoreApplication.translate
        Cat_wind.setWindowTitle(_translate("Cat_wind", "Cat"))

    def center(self, window):
        # Получаем геометрию основного экрана
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        # Получаем геометрию окна
        window_geometry = window.frameGeometry()
        # Центрируем окно
        window_geometry.moveCenter(screen.center())
        # Перемещаем окно в центр экрана
        window.move(window_geometry.topLeft())
