# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maket8.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDownload(object):
    def setupUi(self, MainDownload):
        MainDownload.setObjectName("MainDownload")
        MainDownload.resize(1280, 720)

        self.center(MainDownload)
        
        self.background = QtWidgets.QLabel(MainDownload)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setText("")

        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "whole_background.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.background.setPixmap(pixmap)
                self.background.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")

        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(MainDownload)
        self.frame.setGeometry(QtCore.QRect(160, 64, 960, 572))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 80px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(560, 144, 296, 296))
        self.label.setText("")

        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "med_cross_bright.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.label.setPixmap(pixmap)
                self.label.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")

        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(176, 416, 282, 75))
        font = QtGui.QFont()
        font.setFamily("UbuntuSans-VariableFont_wdth,wght")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(76, 162, 87);\n"
"border-radius: 32px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 146, 80);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(2, 151, 89);\n"
"border: 3px solid rgb(255,215,0);\n"
"color: rgb(248, 248, 242);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(32, 176, 523, 194))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(MainDownload)
        self.label_2.setGeometry(QtCore.QRect(280, 640, 728, 59))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(102, 102, 102);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(MainDownload)
        QtCore.QMetaObject.connectSlotsByName(MainDownload)

    def retranslateUi(self, MainDownload):
        _translate = QtCore.QCoreApplication.translate
        MainDownload.setWindowTitle(_translate("MainDownload", "HealthTrack"))
        self.pushButton.setText(_translate("MainDownload", "Далее"))
        self.label_3.setText(_translate("MainDownload", "Это приложение создано в целях\n"
"выдачи рекомендаций по\n"
"улучшению состояния здоровья\n"
"на основе введённых\n"
"показателей."))
        self.label_2.setText(_translate("MainDownload", "Авторы приложения не несут ответсвенности за Ваше здоровье. \n"
"Обязательно проконсультируйтесь с врачом."))
    
    def center(self, window):
        # Получаем геометрию основного экрана
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        # Получаем геометрию окна
        window_geometry = window.frameGeometry()
        # Центрируем окно
        window_geometry.moveCenter(screen.center())
        # Перемещаем окно в центр экрана
        window.move(window_geometry.topLeft())