# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secret.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
# бла-бла-бла
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Password_wind(object):
    def setupUi(self, Password_wind):
        Password_wind.setObjectName("Password_wind")
        Password_wind.resize(1100, 720)

        self.center(Password_wind)


        Password_wind.setMinimumSize(QtCore.QSize(1100, 720))
        Password_wind.setMaximumSize(QtCore.QSize(1280, 720))
        self.background = QtWidgets.QLabel(Password_wind)
        self.background.setGeometry(QtCore.QRect(0, 0, 1100, 720))
        self.background.setMinimumSize(QtCore.QSize(1100, 720))
        self.background.setMaximumSize(QtCore.QSize(1100, 720))
        self.background.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "beautiful_sample_background.jpg")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.background.setPixmap(pixmap)
                self.background.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")

        self.background.setObjectName("background")
        self.password_line = QtWidgets.QLineEdit(Password_wind)
        self.password_line.setGeometry(QtCore.QRect(150, 140, 771, 121))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.password_line.setFont(font)
        self.password_line.setStyleSheet("border: 7px solid rgb(255, 255, 255);\n"
"background-color: rgba(191, 64, 64, 0);\n"
"border-radius: 50px;\n"
"color: rgb(255, 255, 255);")
        self.password_line.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line.setObjectName("password_line")
        self.dream = QtWidgets.QPushButton(Password_wind)
        self.dream.setGeometry(QtCore.QRect(150, 420, 351, 121))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.dream.setFont(font)
        self.dream.setStyleSheet("QPushButton{\n"
"\n"
"border: 7px solid rgb(255, 255, 255);\n"
"background-color: rgba(191, 64, 64, 0);\n"
"border-radius: 50px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color: rgba(175, 169, 169, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(232, 232, 232, 163);\n"
"border: 7px solid rgb(86,147,70);\n"
"color:rgb(86,147,70);\n"
"}")
        self.dream.setObjectName("dream")

        self.retranslateUi(Password_wind)
        QtCore.QMetaObject.connectSlotsByName(Password_wind)

    def retranslateUi(self, Password_wind):
        _translate = QtCore.QCoreApplication.translate
        Password_wind.setWindowTitle(_translate("Password_wind", "Secret"))
        self.dream.setText(_translate("Password_wind", "Enter"))

    def center(self, window):
        # Получаем геометрию основного экрана
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        # Получаем геометрию окна
        window_geometry = window.frameGeometry()
        # Центрируем окно
        window_geometry.moveCenter(screen.center())
        # Перемещаем окно в центр экрана
        window.move(window_geometry.topLeft())