# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 316)
        Dialog.setMinimumSize(QtCore.QSize(655, 316))
        Dialog.setMaximumSize(QtCore.QSize(655, 316))
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 655, 316))
        self.frame.setMinimumSize(QtCore.QSize(655, 316))
        self.frame.setMaximumSize(QtCore.QSize(655, 316))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.frame.setFont(font)
        self.frame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame.setStyleSheet("background-color: #ffffec;\n"
                                 "border-radius: 10px;\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 10, 315, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(224, 27, 36);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 900, 130))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(224, 27, 36);")
        self.label_2.setObjectName("label_2")
        self.agree_btm = QtWidgets.QPushButton(self.frame)
        self.agree_btm.setGeometry(QtCore.QRect(260, 240, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.agree_btm.setFont(font)
        self.agree_btm.setStyleSheet("QPushButton{\n"
                                     "background-color: rgb(255,215,0);\n"
                                     "border: 5px solid rgb(2, 151, 89);\n"
                                     "border-radius: 10px;\n"
                                     "color: rgb(61, 56, 70);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: rgb(228, 193, 3);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed{\n"
                                     "background-color: rgb(2, 151, 89);\n"
                                     "border: 5px solid rgb(255,215,0);\n"
                                     "color: rgb(248, 248, 242);\n"
                                     "}")
        self.agree_btm.setObjectName("agree_btm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HealthTrack"))
        self.label.setText(_translate("Dialog", "ВНИМАНИЕ"))
        self.label_2.setText(_translate("Dialog", "    Создатели приложения не несут \n"
                                                  "  ответственность за Ваше здоровье. \n"
                                                  "Обязательно проконсультируйтесь со \n"
                                                  "                     специалистом."
                                        ))
        self.agree_btm.setText(_translate("Dialog", "Ok"))
