# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Win_2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window2(object):
    def setupUi(self, Window2):
        Window2.setObjectName("Window2")
        Window2.resize(1280, 720)

        self.center(Window2)
        
        self.background = QtWidgets.QLabel(Window2)
        self.background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "whole_background.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.background.setPixmap(pixmap)
                self.background.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(Window2)
        self.frame.setGeometry(QtCore.QRect(160, 64, 960, 572))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 80px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(560, 120, 296, 296))
        self.label.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "cross_o.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.label.setPixmap(pixmap)
                self.label.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(64, 64, 71, 42))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 42, 5);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(64, 192, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.nationality = QtWidgets.QLineEdit(self.frame)
        self.nationality.setGeometry(QtCore.QRect(34, 238, 482, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.nationality.setFont(font)
        self.nationality.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 5px solid rgb(0,39,3);\n"
"border-radius: 30px;\n"
"color: rgb(0, 42, 5);\n"
"padding-left: 10px;")
        self.nationality.setObjectName("nationality")
        
        regex = QtCore.QRegExp("[А-Яа-яA-Za-z\- ]{0,75}")
        validator = QtGui.QRegExpValidator(regex)
        self.nationality.setValidator(validator)
        self.nationality.setMaxLength(75)  # макс длин
        
        self.page2to1_btm = QtWidgets.QPushButton(self.frame)
        self.page2to1_btm.setGeometry(QtCore.QRect(523, 434, 183, 83))
        font = QtGui.QFont()
        font.setFamily("UbuntuSans-VariableFont_wdth,wght")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.page2to1_btm.setFont(font)
        self.page2to1_btm.setStyleSheet("QPushButton{\n"
"background-color: rgb(76, 162, 87);\n"
"border-radius: 40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 146, 80);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(2, 151, 89);\n"
"border: 2px solid rgb(255,215,0);\n"
"color: rgb(248, 248, 242);\n"
"}")
        self.page2to1_btm.setObjectName("page2to1_btm")
        self.page2to3_btm = QtWidgets.QPushButton(self.frame)
        self.page2to3_btm.setGeometry(QtCore.QRect(715, 434, 183, 83))
        font = QtGui.QFont()
        font.setFamily("UbuntuSans-VariableFont_wdth,wght")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.page2to3_btm.setFont(font)
        self.page2to3_btm.setStyleSheet("QPushButton{\n"
"background-color: rgb(76, 162, 87);\n"
"border-radius: 40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 146, 80);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(2, 151, 89);\n"
"border: 2px solid rgb(255,215,0);\n"
"color: rgb(248, 248, 242);\n"
"}")
        self.page2to3_btm.setObjectName("page2to3_btm")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(64, 323, 300, 42))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.residence = QtWidgets.QLineEdit(self.frame)
        self.residence.setGeometry(QtCore.QRect(34, 366, 482, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.residence.setFont(font)
        self.residence.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 5px solid rgb(0,39,3);\n"
"border-radius: 30px;\n"
"color: rgb(0, 42, 5);\n"
"padding-left: 10px;")
        self.residence.setObjectName("residence")
        
        regex = QtCore.QRegExp("[А-Яа-яA-Za-z\- ]{0,75}")
        validator = QtGui.QRegExpValidator(regex)
        self.residence.setValidator(validator)
        self.residence.setMaxLength(75)  # макс длин
        
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(309, 64, 58, 42))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 42, 5);")
        self.label_5.setObjectName("label_5")
        self.height = QtWidgets.QSpinBox(self.frame)
        self.height.setGeometry(QtCore.QRect(34, 112, 237, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.height.setFont(font)
        self.height.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 5px solid rgb(0,39,3);\n"
"border-radius: 26px;\n"
"color: rgb(0, 42, 5);\n"
"size: 40px;")
        self.height.setAlignment(QtCore.Qt.AlignCenter)
        self.height.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.height.setMinimum(100)
        self.height.setMaximum(250)
        self.height.setProperty("value", 160)
        self.height.setObjectName("height")
        self.weight = QtWidgets.QSpinBox(self.frame)
        self.weight.setGeometry(QtCore.QRect(277, 112, 237, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.weight.setFont(font)
        self.weight.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 5px solid rgb(0,39,3);\n"
"border-radius: 26px;\n"
"color: rgb(0, 42, 5);\n"
"size: 40px;")
        self.weight.setAlignment(QtCore.Qt.AlignCenter)
        self.weight.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.weight.setMinimum(45)
        self.weight.setMaximum(200)
        self.weight.setProperty("value", 60)
        self.weight.setObjectName("weight")
        self.responsibillity = QtWidgets.QLabel(Window2)
        self.responsibillity.setGeometry(QtCore.QRect(220, 640, 845, 68))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.responsibillity.setFont(font)
        self.responsibillity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.responsibillity.setStyleSheet("color: rgb(102, 102, 102);")
        self.responsibillity.setAlignment(QtCore.Qt.AlignCenter)
        self.responsibillity.setObjectName("responsibillity")
        self.status_bar = QtWidgets.QLabel(Window2)
        self.status_bar.setGeometry(QtCore.QRect(238, 42, 803, 14))
        self.status_bar.setText("")
        base_dir = os.path.dirname(os.path.abspath(__file__))
        fon_path = os.path.join(base_dir, "images", "bar2.png")
        if os.path.exists(fon_path):
            pixmap = QtGui.QPixmap(fon_path)
            if not pixmap.isNull():
                self.status_bar.setPixmap(pixmap)
                self.status_bar.setScaledContents(True)
            else:
                print(f"Ошибка загрузки изображения: {fon_path}")
        else:
            print(f"Файл не найден: {fon_path}")
        self.status_bar.setObjectName("status_bar")

        self.retranslateUi(Window2)
        QtCore.QMetaObject.connectSlotsByName(Window2)

    def retranslateUi(self, Window2):
        _translate = QtCore.QCoreApplication.translate
        Window2.setWindowTitle(_translate("Window2", "HealthTrack"))
        self.label_2.setText(_translate("Window2", "Рост"))
        self.label_3.setText(_translate("Window2", "Национальность"))
        self.page2to1_btm.setText(_translate("Window2", "Назад"))
        self.page2to3_btm.setText(_translate("Window2", "Далее"))
        self.label_4.setText(_translate("Window2", "Место проживания"))
        self.label_5.setText(_translate("Window2", "Вес"))
        self.responsibillity.setText(_translate("Window2", "Авторы приложения не несут ответсвенности за Ваше здоровье. \n"
"Обязательно проконсультируйтесь с врачом."))

    def center(self, window):
        # Получаем геометрию основного экрана
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        # Получаем геометрию окна
        window_geometry = window.frameGeometry()
        # Центрируем окно
        window_geometry.moveCenter(screen.center())
        # Перемещаем окно в центр экрана
        window.move(window_geometry.topLeft())